### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toCombo') After Replug update

### ISSUE THREAD

**Issue by patipakdeeying** [Tharki-God/FakeDeafen#7]
TypeError: Cannot read properties of undefined (reading 'toCombo')
at get keybind [as keybind] (replugged://plugin/dev.tharki.FakeDeafen.asar/renderer.js?t=1719036957683:1:31848)
at ie (replugged://plugin/dev.tharki.FakeDeafen.asar/renderer.js?t=1719036957683:1:37048)
at aS (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:960290)
at u (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:1015506)
at sF (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:998521)
at https://discord.com/assets/67096.30c593c3471420b5c889.js:12:998387
at sB (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:998395)
at sT (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:995146)
at sO (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:995535)
at r6 (https://discord.com/assets/67096.30c593c3471420b5c889.js:12:944154)

**Comment by yofukashino** [comment]
you on older version
